server:
  port: 8182
spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: 172.20.20.20:9092
      auto-offset-reset: earliest
      group-id: testclient003
      properties:
        spring.json.trusted.packages: "*"
app:
  topicName: test-topic